### ISSUE TITLE
read Appsettings from appsettings.json or env-vars

### ISSUE THREAD

**Issue by FalkoHilbert** [mbcomdev/ConnectBASE#1]
Hi, 
it's a very nice Project. I Think in genral the AppSettings shouldn't be part of the Code. I Think a better Way is to read it from appsettings.json or environment-vars. This Link should help: https://docs.microsoft.com/de-de/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#bind-hierarchical-configuration-data-using-the-options-pattern
If you need any support, @viosys could help.

**Comment by andipunz** [comment]
Hi,
thanks! This is just the final project result of the project in cooperation with the TH Rosenheim. We will commit some minor changes in the following weeks.
The aim of the open-source project is that it is used and developed futher by microtech büro+ partners and users.
So feel free to fork the project and start pull request for changes.
